x_min_dist_BB: 0.1
x_max_dist_BB: 1.4
y_tolarance_BB: 0.4
z_min_dist_BB: 0.1
z_max_dist_BB: 1.2
planeSegDistTresh: 0.03
numberPointsThresh: 1000
clusterTolerance: 0.03
minClusterSize: 10
maxClusterSize: 1000
searchRadius: 0.2
filter_radius: 0.03
filter_cloud_n_neighbors: 200
filter_cloud_max_stdev: 0.1
